services:
  - type: web
    name: flowise
    env: node
    plan: starter
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=8192
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: DATABASE_TYPE
        value: sqlite
      - key: PORT
        value: 3000
    healthCheckPath: /api/v1/ping
    autoDeploy: true
